### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by oleksandr-jr** [aleos-dev/CipherMachine#2]
The program is working well.
The code is written using the advantages of OOP.
There are some interesting solutions in the code, which is very commendable. 
It is very good that all methods have a detailed description.

The frequency analysis algorithm is well implemented.

Support for Ukrainian and English languages works well.

Almost all additional tasks are completed.

I like the CLI implementation. It's really cool.

I like the idea of using states and `StateHandler`. It illustrates polymorphism well.

In general, the code is well written. A good architecture is thought out and there are opportunities to expand the functionality of the program.

There are some opportunities to improve the quality of the code, but we have not yet studied these topics. Therefore, I can say that at this stage of learning, this is a well-written project.

`PreviousPreviewPageHandler` is never used.
https://github.com/aleos-dev/CipherMachine/blob/84307d5f81e5a86241e15c606238e203e417a078/src/statehandlers/PreviousPreviewPageHandler.java#L6

I didn't get the point of this empty implementation.
https://github.com/aleos-dev/CipherMachine/blob/84307d5f81e5a86241e15c606238e203e417a078/src/statehandlers/OffMachineHandler.java#L5

Test results
<img width="716" alt="image" src="https://github.com/aleos-dev/CipherMachine/assets/116897595/b3f30025-0b17-4038-9be3-3a79d0f38de8">

**Comment by aleos-dev** [comment]
Previously, the PreviousPreviewPageHandler was used, but after making some changes, it became unnecessary. I simply forgot to delete it. The OffMachineHandler should handle some final tasks, perhaps saying goodbye or something similar. I will come up with it in the future.

Thank you for your feedback.
